In [2]:
import pandas as pd

In [3]:
tomato = pd.read_csv('/Users/anastasia.petrie/Desktop/USDA_Calc/Data/tomato_report.csv')

In [4]:
print tomato

    Commodity Name                           City Name  Type  \
0         TOMATOES         CENTRAL DISTRICT CALIFORNIA   NaN   
1         TOMATOES         CENTRAL DISTRICT CALIFORNIA   NaN   
2         TOMATOES         CENTRAL DISTRICT CALIFORNIA   NaN   
3         TOMATOES         CENTRAL DISTRICT CALIFORNIA   NaN   
4         TOMATOES         CENTRAL DISTRICT CALIFORNIA   NaN   
5         TOMATOES         CENTRAL DISTRICT CALIFORNIA   NaN   
6         TOMATOES         CENTRAL DISTRICT CALIFORNIA   NaN   
7         TOMATOES         CENTRAL DISTRICT CALIFORNIA   NaN   
8         TOMATOES         CENTRAL DISTRICT CALIFORNIA   NaN   
9         TOMATOES         CENTRAL DISTRICT CALIFORNIA   NaN   
10        TOMATOES         CENTRAL DISTRICT CALIFORNIA   NaN   
11        TOMATOES         CENTRAL DISTRICT CALIFORNIA   NaN   
12        TOMATOES         CENTRAL DISTRICT CALIFORNIA   NaN   
13        TOMATOES         CENTRAL DISTRICT CALIFORNIA   NaN   
14        TOMATOES         CENTRAL DISTR

In [5]:
t = pd.DataFrame(tomato)

In [6]:
t.tail(5)

Commodity Name                           City Name  Type          Package  \
793       TOMATOES  MEXICO CROSSINGS THROUGH OTAY MESA   NaN  cartons 2 layer   
794       TOMATOES  MEXICO CROSSINGS THROUGH OTAY MESA   NaN  cartons 2 layer   
795       TOMATOES  MEXICO CROSSINGS THROUGH OTAY MESA   NaN  cartons 2 layer   
796       TOMATOES  MEXICO CROSSINGS THROUGH OTAY MESA   NaN  cartons 2 layer   
797       TOMATOES  MEXICO CROSSINGS THROUGH OTAY MESA   NaN  cartons 2 layer   

        Variety  Sub Variety  Grade      Date  Low Price  High Price  \
793  VINE RIPES          NaN    NaN  11/27/15      10.95       12.95   
794  VINE RIPES          NaN    NaN  11/30/15        NaN         NaN   
795  VINE RIPES          NaN    NaN  11/30/15        NaN         NaN   
796  VINE RIPES          NaN    NaN  11/30/15        NaN         NaN   
797  VINE RIPES          NaN    NaN  11/30/15        NaN         NaN   

        ...       Purchase Lot Size  Section or Sale  Import/Export  \
793     ...                     NaN              NaN            NaN   
794     ...                     NaN              NaN            NaN   
795     ...                     NaN              NaN            NaN   
796     ...                     NaN              NaN            NaN   
797     ...                     NaN              NaN            NaN   

    Supply Tone                              Demand Tone  \
793      LIGHT.  4X4-4X5S MODERATE, OTHERS FAIRLY LIGHT.   
794      LIGHT.                                      NaN   
795      LIGHT.                                      NaN   
796      LIGHT.                                      NaN   
797      LIGHT.                                      NaN   

                                         Basis of Sale    Market Tone  \
793  Sales F.O.B. Shipping Point and/or Delivered S...  ABOUT STEADY.   
794  Sales F.O.B. Shipping Point and/or Delivered S...            NaN   
795  Sales F.O.B. Shipping Point and/or Delivered S...            NaN   
796  Sales F.O.B. Shipping Point and/or Delivered S...            NaN   
797  Sales F.O.B. Shipping Point and/or Delivered S...            NaN   

                                         Price Comment  \
793                                  occasional higher   
794        supplies insufficient to establish a market   
795        supplies insufficient to establish a market   
796        supplies insufficient to establish a market   
797  supplies insufficient to establish a market. L...   

                                              Comments     Rpt City  
793  Extra services included. Wide range in quality...  PHOENIX, AZ  
794  Extra services included. Wide range in quality...  PHOENIX, AZ  
795  Extra services included. Wide range in quality...  PHOENIX, AZ  
796  Extra services included. Wide range in quality...  PHOENIX, AZ  
797  Extra services included. Wide range in quality...  PHOENIX, AZ  

[5 rows x 32 columns]

In [7]:
list(t.columns.values)

['Commodity Name',
 'City Name',
 'Type',
 'Package',
 'Variety',
 'Sub Variety',
 'Grade',
 'Date',
 'Low Price',
 'High Price',
 'Mostly Low',
 'Mostly High',
 'Season',
 'Item Size',
 'Color',
 'Environment',
 'Unit of Sale',
 'Quality',
 'Condition',
 'Appearance',
 'Storage',
 'Shelled/Unshelled',
 'Purchase Lot Size',
 'Section or Sale',
 'Import/Export',
 'Supply Tone',
 'Demand Tone',
 'Basis of Sale',
 'Market Tone',
 'Price Comment',
 'Comments',
 'Rpt City']

In [8]:
t.shape

(798, 32)

In [9]:
t['Import/Export'].unique()

array([ nan])

In [10]:
t['City Name'].unique()

array(['CENTRAL DISTRICT CALIFORNIA', 'MEXICO CROSSINGS THROUGH OTAY MESA'], dtype=object)

In [11]:
t['Item Size'].unique()

array([nan, 'xlge', 'lge', 'med', 'jbo', '4x4s', '4x5s', '5x5s', '5x6s'], dtype=object)

In [12]:
t['Supply Tone'].unique()

array(['LIGHT.', nan, 'EXTRA LARGE FAIRLY HEAVY.',
       'JUMBO AND EXTRA LARGE FAIRLY HEAVY.', 'FAIRLY LIGHT.',
       'EXTRA LARGE FAIRLY LIGHT.', 'VERY LIGHT.', 'FAIRLY HEAVY.',
       '4X4-4X5S HEAVY.', '4X4 FAIRLY HEAVY.', '4X4-4X5S FAIRLY HEAVY.',
       '5X6S LIGHT.', '5X5-5X6S VERY LIGHT, OTHERS LIGHT.',
       '4X4-4X5S LIGHT.', '4X5S LIGHT.'], dtype=object)

In [13]:
old_names = [
 'Commodity Name',
 'City Name',
 'Type',
 'Package',
 'Variety',
 'Sub Variety',
 'Grade',
 'Date',
 'Low Price',
 'High Price',
 'Mostly Low',
 'Mostly High',
 'Season',
 'Item Size',
 'Color',
 'Environment',
 'Unit of Sale',
 'Quality',
 'Condition',
 'Appearance',
 'Storage',
 'Shelled/Unshelled',
 'Purchase Lot Size',
 'Section or Sale',
 'Import/Export',
 'Supply Tone',
 'Demand Tone',
 'Basis of Sale',
 'Market Tone',
 'Price Comment',
 'Comments',
 'Rpt City'] 
new_names = [
 'commodity',
 'city',
 'type',
 'package',
 'variety',
 'sub_variety',
 'grade',
 'date',
 'low_price',
 'high_price',
 'mostly_low',
 'mostly_high',
 'season',
 'size',
 'color',
 'environment',
 'unit_of_sale',
 'quality',
 'condition',
 'appearance',
 'storage',
 'shelled',
 'purchase-lot_size',
 'section',
 'import',
 'supply_tone',
 'demand_tone',
 'basis_of_sale',
 'market_tone',
 'Price Comment',
 'comments',
 'rpt_city']
t.rename(columns=dict(zip(old_names, new_names)), inplace=True)

In [14]:
t['rpt_city'].unique()

array(['PHOENIX, AZ'], dtype=object)

In [16]:
t['demand_tone'].unique()

array([nan, 'LIGHT.', 'FAIRLY LIGHT.',
       'EXTRA LARGE FAIRLY LIGHT, OTHERS MODERATE.', 'MODERATE.',
       'FAIRLY GOOD.', 'GOOD.', 'EXCEEDS SUPPLY.', 'VERY GOOD.',
       'MEDIUM MODERATE, OTHERS FAIRLY GOOD.',
       'MEDIUM MODERATE, OTHERS GOOD.', 'MEDIUM LIGHT, OTHERS MODERATE.',
       '5X6S MODERATE, 5X5S FAIRLY LIGHT, OTHERS LIGHT.',
       '4X4-4X5S LIGHT, OTHERS MODERATE.', '4X4S LIGHT, OTHERS MODERATE.',
       '4X4-4X5S MODERATE, OTHERS FAIRLY GOOD.',
       '4X4-4X5S FAIRLY LIGHT, OTHERS MODERATE.',
       '5X6S GOOD AT LOWER PRICES, OTHERS GOOD.',
       '4X5S FAIRLY GOOD, OTHERS MODERATE.',
       '4X4-4X5S VERY GOOD, OTHERS MODERATE.',
       '4X4-4X5S GOOD, OTHERS MODERATE.',
       '4X4-4X5S FAIRLY GOOD, OTHERS LIGHT.',
       '4X4-4X5S MODERATE, OTHERS FAIRLY LIGHT.'], dtype=object)

In [13]:
list(t.columns.values)

['commodity',
 'city',
 'type',
 'package',
 'variety',
 'sub_variety',
 'grade',
 'date',
 'low_price',
 'high_price',
 'mostly_low',
 'mostly_high',
 'season',
 'size',
 'color',
 'environment',
 'unit_of_sale',
 'quality',
 'condition',
 'appearance',
 'storage',
 'shelled',
 'purchase-lot_size',
 'section',
 'import',
 'supply_tone',
 'demand_tone',
 'basis_of_sale',
 'market_tone',
 'Price Comment',
 'comments',
 'rpt_city']

In [14]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.cross_validation import train_test_split
from sklearn import metrics
import statsmodels.formula.api as smf

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline